//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessSubCatageory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessSubCatageory()
        {
            this.Customer_SubCatageory = new HashSet<Customer_SubCatageory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> BussinessCatageoryId { get; set; }
    
        public virtual BusinessCatageory BusinessCatageory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_SubCatageory> Customer_SubCatageory { get; set; }
    }
}
