//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Agencies = new HashSet<Agency>();
            this.Customer_SubCatageory = new HashSet<Customer_SubCatageory>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DetailId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> BussinessID { get; set; }
        public Nullable<int> GalleryID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> SmsID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> WorkingID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agency> Agencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_SubCatageory> Customer_SubCatageory { get; set; }
        public virtual CustomerBusinessDetail CustomerBusinessDetail { get; set; }
        public virtual CustomerContact CustomerContact { get; set; }
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual CustomerGallery CustomerGallery { get; set; }
        public virtual CustomerLocation CustomerLocation { get; set; }
        public virtual CustomerRegion CustomerRegion { get; set; }
        public virtual CustomerSM CustomerSM { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual User User { get; set; }
        public virtual WorkingTime WorkingTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
