//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftVoucher
    {
        public int Id { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Sku { get; set; }
        public string Description { get; set; }
        public Nullable<bool> RedmeeOnline { get; set; }
        public Nullable<bool> Voided { get; set; }
        public Nullable<int> ExpireId { get; set; }
    
        public virtual Expire Expire { get; set; }
    }
}
